[project]
name = "zoomcamp-sma-cohort-2026"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "rlp-jym", email = "ralpj.jayoma@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "duckdb>=1.5.5",
    "jupyterlab>=4.6.3",
    "lxml>=6.1.3",
    "numpy>=2.5.3",
    "pandas>=3.0.6",
    "tqdm>=4.70.1",
    "yfinance>=1.7.0",
]

[project.scripts]
zoomcamp-sma-cohort-2026 = "zoomcamp_sma_cohort_2026:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
